version: '3.8'

services:
  java_app:
    container_name: java__app
    image: boris/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.data.mongodb.uri": "mongodb://rootuser:rootpass@mongodb:27017/admin?authSource=admin"
      }'
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
       - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
       - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
       - ME_CONFIG_MONGODB_SERVER=mongodb
       - ME_CONFIG_BASICAUTH_USERNAME=user
       - ME_CONFIG_BASICAUTH_PASSWORD=pass
   
networks:
  default:
    name: mongo_network
       
volumes:
  data: {}